stages:
  - test

test_minikube_runner:
  tags:
    - minikube # Обязательно указываем тег, который мы задавали в values.yaml
  script:
    - echo "Привет! Я успешно работаю внутри Minikube!"
    - docker info # Проверяем, доступен ли Docker внутри раннера