[versions]
spring-boot = "3.4.5"
spring-cloud = "2024.0.1" # Замени на нужную версию

apacheCommon = "2.13.0"
wiremock = "3.4.0"
mockito = "5.11.0"
lombok = "1.18.46"
reactorTest = "3.8.0"
nimbus = "9.31"
testcontainers = "2.0.5"
resilence4j = "2.2.0"



[libraries]
# Spring Boot
spring-boot-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-security = { group = "org.springframework.boot", name = "spring-boot-starter-security" }
spring-boot-resourceServer = { group = "org.springframework.boot", name = "spring-boot-starter-oauth2-resource-server" }
spring-boot-data-redis = { group = "org.springframework.boot", name = "spring-boot-starter-data-redis" }
spring-boot-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }

# Spring Cloud (эти версии обычно диктует BOM, но мы фиксируем имена для удобства)
spring-cloud-bom = { group = "org.springframework.cloud", name = "spring-cloud-dependencies", version.ref = "spring-cloud" }
spring-cloud-consul = { group = "org.springframework.cloud", name = "spring-cloud-starter-consul-discovery" }
spring-cloud-gateway = { group = "org.springframework.cloud", name = "spring-cloud-starter-gateway" }
spring-cloud-loadbalancer = { group = "org.springframework.cloud", name = "spring-cloud-starter-loadbalancer" }
spring-cloud-stubrunner = { group = "org.springframework.cloud", name = "spring-cloud-starter-contract-stub-runner" }

# RateLimit
resilence4j-ratelimiter = { group = "io.github.resilience4j", name = "resilience4j-ratelimiter", version.ref = "resilence4j"}
resilence4j-core = { group = "io.github.resilience4j", name = "resilience4j-core", version.ref = "resilence4j"}
resilence4j-micrometer = { group = "io.github.resilience4j", name = "resilience4j-micrometer", version.ref = "resilence4j"}

# Observability
micrometer-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus" }
micrometer-tracing-bridge = {group = "io.micrometer", name = "micrometer-tracing-bridge-otel"}
opentelemetry-exporter = {group = "io.opentelemetry", name = "opentelemetry-exporter-otlp"}

# Helpers
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
apache-commons-pool = { group = "org.apache.commons", name = "commons-pool2", version.ref = "apacheCommon" }

# Testing
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
mockito-junit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
wiremock-spring = { group = "org.wiremock.integrations", name = "wiremock-spring-boot", version.ref = "wiremock" }
reactor-test = { group = "io.projectreactor", name = "reactor-test", version.ref = "reactorTest" }
nimbus-jwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version.ref = "nimbus" }
testcontainers = {group = "org.testcontainers", name = "testcontainers", version.ref = "testcontainers"}
testcontainers-junit = {group = "org.testcontainers", name = "testcontainers-junit-jupiter", version.ref = "testcontainers"}



[bundles]
# Можно группировать зависимости, если нужно
junit-jupiter = ["junit-jupiter-api", "junit-jupiter-engine"]
testcontainers = ["testcontainers", "testcontainers-junit"]
resilence4j = ["resilence4j-core", "resilence4j-micrometer"]
