-- Скрипт инициализации PostgreSQL для создания схем микросервисов
-- Выполняется автоматически при первом запуске контейнера

-- Создание схем для всех микросервисов

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS user_service;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS pricing;
CREATE SCHEMA IF NOT EXISTS inventory;
CREATE SCHEMA IF NOT EXISTS search;
CREATE SCHEMA IF NOT EXISTS order_service;
CREATE SCHEMA IF NOT EXISTS payment;
CREATE SCHEMA IF NOT EXISTS logistics;
CREATE SCHEMA IF NOT EXISTS returns;
CREATE SCHEMA IF NOT EXISTS notification;
CREATE SCHEMA IF NOT EXISTS messaging;
CREATE SCHEMA IF NOT EXISTS moderation;
CREATE SCHEMA IF NOT EXISTS marketing;
CREATE SCHEMA IF NOT EXISTS reporting;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS admin_service;
CREATE SCHEMA IF NOT EXISTS seller_dashboard;
CREATE SCHEMA IF NOT EXISTS seller_analytics;
CREATE SCHEMA IF NOT EXISTS knowledgebase;
CREATE SCHEMA IF NOT EXISTS parts_calculator;
CREATE SCHEMA IF NOT EXISTS integration;
CREATE SCHEMA IF NOT EXISTS videocall;
CREATE SCHEMA IF NOT EXISTS media;

-- Предоставление прав пользователю services_db_user на все схемы
-- Обратите внимание: замените services_db_user на фактическое имя пользователя из переменных окружения
--
-- GRANT ALL PRIVILEGES ON SCHEMA auth TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA user_service TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA catalog TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA pricing TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA inventory TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA search TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA order_service TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA payment TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA logistics TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA returns TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA notification TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA messaging TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA moderation TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA marketing TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA reporting TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA analytics TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA admin_service TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA seller_dashboard TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA seller_analytics TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA knowledgebase TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA parts_calculator TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA integration TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA videocall TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON SCHEMA media TO ${SERVICES_DB_USER};
--
-- -- Предоставление прав на все таблицы в схемах (для новых и существующих)
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA user_service TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA catalog TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA pricing TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA inventory TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA search TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA order_service TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA payment TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA logistics TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA returns TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA notification TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA messaging TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA moderation TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA marketing TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA reporting TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA admin_service TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA seller_dashboard TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA seller_analytics TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA knowledgebase TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA parts_calculator TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA integration TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA videocall TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA media TO ${SERVICES_DB_USER};
--
-- -- Предоставление прав на все последовательности в схемах
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA auth TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA user_service TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA catalog TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA pricing TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA inventory TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA search TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA order_service TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA payment TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA logistics TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA returns TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA notification TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA messaging TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA moderation TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA marketing TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA reporting TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA analytics TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA admin_service TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA seller_dashboard TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA seller_analytics TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA knowledgebase TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA parts_calculator TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA integration TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA videocall TO ${SERVICES_DB_USER};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA media TO ${SERVICES_DB_USER};
--
-- -- Для новых таблиц, создаваемых в будущем
-- ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA user_service GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA user_service GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA pricing GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA pricing GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA search GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA search GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA order_service GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA order_service GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA payment GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA payment GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA logistics GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA logistics GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA returns GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA returns GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA messaging GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA messaging GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA moderation GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA moderation GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA marketing GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA marketing GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA admin_service GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA admin_service GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA seller_dashboard GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA seller_dashboard GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA seller_analytics GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA seller_analytics GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA knowledgebase GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA knowledgebase GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA parts_calculator GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA parts_calculator GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA integration GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA integration GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA videocall GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA videocall GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA media GRANT ALL ON TABLES TO ${SERVICES_DB_USER};
-- ALTER DEFAULT PRIVILEGES IN SCHEMA media GRANT ALL ON SEQUENCES TO ${SERVICES_DB_USER};
