server:
  port: 8080

---
spring:
  application:
    name: api-gateway
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #отключаем автоматическое создание маршрутов
      routes:
        - id: api-gateway-actuator
          uri: http://localhost:8080  # тот же хост
          predicates:
            - Path=/actuator/**

        - id: platform-service
          uri: lb://platform-service
          predicates:
            - Path=/api/v1/platform/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/v1/catalog/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: communication-service
          uri: lb://communication-service
          predicates:
            - Path=/api/v1/communication/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}


    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: "api-gateway"
        health-check-path: "/actuator/health"
        health-check-interval: 15s
        prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator  # явное указание базового пути
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
    security:
      enabled: false  # отключение безопасности для Actuator (для диагностики)
    server:
      port: ${server.port}

