server:
  port: 8080

---
spring:
  application:
    name: api-gateway
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #отключаем автоматическое создание маршрутов
      routes:
        - id: api-gateway-actuator
          uri: http://localhost:8080  # тот же хост
          predicates:
            - Path=/actuator/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/v1/catalog/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: pricing-inventory-service
          uri: lb://pricing-inventory-service
          predicates:
            - Path=/api/v1/price/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/v1/search/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/reviews/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/api/v1/recommendations/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/v1/analytics/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}


    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: "api-gateway"
        health-check-path: "/actuator/health"
        health-check-interval: 15s
        prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator  # явное указание базового пути
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
    security:
      enabled: false  # отключение безопасности для Actuator (для диагностики)
    server:
      port: ${server.port}

